Add commit status check

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -63,12 +63,48 @@ jobs:
       - name: Prepare k3s cluster and docker registry
         run: "./scripts/testing/k3s-setup.sh --wait"
 
+      - name: Wait for post-btp-manager-module-build status
+        uses: autotelic/action-wait-for-status-check@6556cf50c8fb6608412945382eae73581f56cbb4
+        id: wait-for-module-build-status
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          statusName: "post-btp-manager-module-build"
+          timeoutSeconds: "300"
+
+      - name: Check if post-btp-manager-module-build status is success
+        if: steps.wait-for-module-build-status.state != 'success'
+        run: |
+          echo 'post-btp-manager-module-build failed.'
+          exit 1
+
+      - name: Wait for post-btp-manager-build status
+        uses: autotelic/action-wait-for-status-check@6556cf50c8fb6608412945382eae73581f56cbb4
+        id: wait-for-image-build-status
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          statusName: "post-btp-manager-build"
+          timeoutSeconds: "300"
+
+      - name: Check if post-btp-manager-build status is success
+        if: steps.wait-for-image-build-status.state != 'success'
+        run: |
+          echo 'post-btp-manager-build failed.'
+          exit 1
+
       - name: Wait for artifacts
         env:
           BTP_OPERATOR_REPO: ${{ env.MODULE_REPO }}
           BTP_MANAGER_REPO: ${{ env.IMAGE_REPO }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: "./scripts/await_artifacts.sh ${{ inputs.name }} v${{ inputs.name }}"
+
+      - name: Wait for jobs
+        uses: "./.github/workflows/await-artifacts-reusable.yaml"
+        with:
+          image-tag: ${{ inputs.name }}
+          module-tag: v${{ inputs.name }}
+          btp-operator-repo: ${{ env.MODULE_REPO }}
+          btp-manger-repo: ${{ env.IMAGE_REPO }}
 
       - name: Install BTP operator
         timeout-minutes: 2
