wip

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -46,7 +46,41 @@ jobs:
         id: wait-for-module-build-status
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-          statusName: "Run unit tests"
+          statusName: "post-btp-manager-module-build"
+          timeoutSeconds: "300"
+
+      - name: Check if post-btp-manager-module-build status is success
+        if: steps.wait-for-module-build-status.state != 'success'
+        run: |
+            echo 'post-btp-manager-module-build failed.'
+            exit 1
+
+      - name: Wait for post-btp-manager-build status
+        uses: autotelic/action-wait-for-status-check@6556cf50c8fb6608412945382eae73581f56cbb4
+        id: wait-for-image-build-status
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          statusName: "post-btp-manager-build"
+          timeoutSeconds: "300"
+
+      - name: Check if post-btp-manager-build status is success
+        if: steps.wait-for-image-build-status.state != 'success'
+        run: |
+          echo 'post-btp-manager-build failed.'
+          exit 1
+
+  wait-for-prow-jobs:
+    name: Wait for prow jobs
+    needs: create-draft
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Wait for post-btp-manager-module-build status
+        uses: autotelic/action-wait-for-status-check@6556cf50c8fb6608412945382eae73581f56cbb4
+        id: wait-for-module-build-status
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          statusName: "post-btp-manager-module-build"
           timeoutSeconds: "300"
 
       - name: Check if post-btp-manager-module-build status is success
@@ -71,7 +105,7 @@ jobs:
   
   run-unit-tests:
     name: Unit tests
-    needs: validate-release
+    needs: wait-for-prow-jobs
     uses: "./.github/workflows/run-unit-tests-reusable.yaml"
 
   run-e2e-tests:
@@ -88,7 +122,7 @@ jobs:
 
   run-stress-tests:
     name: Stress tests
-    needs: validate-release
+    needs: wait-for-prow-jobs
     runs-on: ubuntu-latest
 
     steps:
